//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runtasker.Resources.Views.Orders.Create {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Create {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Create() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Runtasker.Resources.Views.Orders.Create.Create", typeof(Create).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться к моим заказам.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новый.
        /// </summary>
        public static string CreateNav {
            get {
                return ResourceManager.GetString("CreateNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить заказ.
        /// </summary>
        public static string CreateOrder {
            get {
                return ResourceManager.GetString("CreateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы загружаются на наш сервер.
        /// </summary>
        public static string FileUploading {
            get {
                return ResourceManager.GetString("FileUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратите внимание на поле \&quot;Дата окончания\&quot;. На выполнение работ типа  \&quot;Курсовая работа\&quot; отводится минимум 30 дней..
        /// </summary>
        public static string FinishDateErrorCourseWork {
            get {
                return ResourceManager.GetString("FinishDateErrorCourseWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратите внимание на поле \&quot;Дата окончания\&quot;. На выполнение работ типа  \&quot;Эссе/Реферат\&quot; отводится минимум 7 дней..
        /// </summary>
        public static string FinishDateErrorEssay {
            get {
                return ResourceManager.GetString("FinishDateErrorEssay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратите внимание на поле \&quot;Дата окончания\&quot;. На выполнение работ типа  \&quot;Обычное задание\&quot; отводится минимум 3 дня..
        /// </summary>
        public static string FinishDateErrorOrdinary {
            get {
                return ResourceManager.GetString("FinishDateErrorOrdinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавьте заказ.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string HomeNav {
            get {
                return ResourceManager.GetString("HomeNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будьте внимательны.
        /// </summary>
        public static string MiniHeader {
            get {
                return ResourceManager.GetString("MiniHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои заказы.
        /// </summary>
        public static string MyOrdersNav {
            get {
                return ResourceManager.GetString("MyOrdersNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы хотите получить помощь онлайн, то можете оставить заявку, кликнув по кнопке..
        /// </summary>
        public static string OnlineHelpAlertText {
            get {
                return ResourceManager.GetString("OnlineHelpAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание, мы оказываем онлайн помощь!.
        /// </summary>
        public static string OnlineHelpAlertTitle {
            get {
                return ResourceManager.GetString("OnlineHelpAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Онлайн-помощь.
        /// </summary>
        public static string OnlineHelpBtnText {
            get {
                return ResourceManager.GetString("OnlineHelpBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новый заказ.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
