//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runtasker.Resources.Email.Account {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountEmRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountEmRes() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Runtasker.Resources.Email.Account.AccountEmRes", typeof(AccountEmRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hello.
        /// </summary>
        public static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hello {0}!.
        /// </summary>
        public static string GreetingFormat {
            get {
                return ResourceManager.GetString("GreetingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To log on the site use the button.
        /// </summary>
        public static string HowToLoginViaProvider {
            get {
                return ResourceManager.GetString("HowToLoginViaProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To log on the site use {0} button..
        /// </summary>
        public static string LoginViaProviderFormat {
            get {
                return ResourceManager.GetString("LoginViaProviderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click here!.
        /// </summary>
        public static string RegistrationButtonText {
            get {
                return ResourceManager.GetString("RegistrationButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm your account.
        /// </summary>
        public static string RegistrationSubject {
            get {
                return ResourceManager.GetString("RegistrationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thank you for registration on Runtasker! We hope you will love our services! So, after you click a button you will get {0}{1} which you can spend on your first order..
        /// </summary>
        public static string RegistrationTextFormat {
            get {
                return ResourceManager.GetString("RegistrationTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm your account.
        /// </summary>
        public static string RegWithOrderBtnText {
            get {
                return ResourceManager.GetString("RegWithOrderBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string RegWithOrderHeader1 {
            get {
                return ResourceManager.GetString("RegWithOrderHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration on Runtasker.
        /// </summary>
        public static string RegWithOrderSubject1 {
            get {
                return ResourceManager.GetString("RegWithOrderSubject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thank you for registration on Runtasker.ru!.
        /// </summary>
        public static string RegWithOrdertText1 {
            get {
                return ResourceManager.GetString("RegWithOrdertText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your account details.
        /// </summary>
        public static string RegWithOrdertText2 {
            get {
                return ResourceManager.GetString("RegWithOrdertText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string RegWithOrdertText3 {
            get {
                return ResourceManager.GetString("RegWithOrdertText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string RegWithOrdertText4 {
            get {
                return ResourceManager.GetString("RegWithOrdertText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset password.
        /// </summary>
        public static string ResetPassSubject {
            get {
                return ResourceManager.GetString("ResetPassSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset your password, by clicking.
        /// </summary>
        public static string ResetPassText1 {
            get {
                return ResourceManager.GetString("ResetPassText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на here.
        /// </summary>
        public static string ResetPassText2 {
            get {
                return ResourceManager.GetString("ResetPassText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Best wishes from the Runtasker team!.
        /// </summary>
        public static string RuntaskerWish {
            get {
                return ResourceManager.GetString("RuntaskerWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thank you for registration on Runtasker! We hope you will love our services! So, after you click a button you will get {0}{1} which you can spend on your first order..
        /// </summary>
        public static string SocialRegistrationTextFormat {
            get {
                return ResourceManager.GetString("SocialRegistrationTextFormat", resourceCulture);
            }
        }
    }
}
