//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runtasker.Resources.Views.Payment.Robokassa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RkassaRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RkassaRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Runtasker.Resources.Views.Payment.Robokassa.RkassaRes", typeof(RkassaRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнение баланса на Runtasker.
        /// </summary>
        public static string ActionDesc1 {
            get {
                return ResourceManager.GetString("ActionDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнение баланса на Runtasker {0}{1}.
        /// </summary>
        public static string ActionDescFormat {
            get {
                return ResourceManager.GetString("ActionDescFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to с помощью Robokassa.
        /// </summary>
        public static string ActionDescMini {
            get {
                return ResourceManager.GetString("ActionDescMini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад к способам Оплаты.
        /// </summary>
        public static string BackToPM {
            get {
                return ResourceManager.GetString("BackToPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы пополняете баланс на Runtasker через Robokassa. Будьте внимательны, так как вы заплатите {0}{1} из-за комиссии удерживаемой сервисом Robokassa. Рекомендуем воспользоваться системой YandexMoney, так как она не имеет комиссии. Нажмите оплатить чтобы продолжить..
        /// </summary>
        public static string InfoFormat {
            get {
                return ResourceManager.GetString("InfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Робокасса.
        /// </summary>
        public static string NavActive {
            get {
                return ResourceManager.GetString("NavActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата.
        /// </summary>
        public static string NavPayments {
            get {
                return ResourceManager.GetString("NavPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнение баланса.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
