//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runtasker.Resources.Views.Payment.YandexKassa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class YandexKassaRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal YandexKassaRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Runtasker.Resources.Views.Payment.YandexKassa.YandexKassaRes", typeof(YandexKassaRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнение баланса на Runtasker.
        /// </summary>
        public static string ActionDesc {
            get {
                return ResourceManager.GetString("ActionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через ЯндексКассу.
        /// </summary>
        public static string ActionDescMini {
            get {
                return ResourceManager.GetString("ActionDescMini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма оплаты.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма оплаты должны быть больше 0!.
        /// </summary>
        public static string AmountErrorText {
            get {
                return ResourceManager.GetString("AmountErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад к способам оплаты.
        /// </summary>
        public static string BackToPM {
            get {
                return ResourceManager.GetString("BackToPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to После того как вы нажмете на кнопку &quot;Оплатить&quot; мы перенаправим вас на .
        /// </summary>
        public static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Яндекс Кассой.
        /// </summary>
        public static string NavActive {
            get {
                return ResourceManager.GetString("NavActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Способы оплаты.
        /// </summary>
        public static string NavPayment {
            get {
                return ResourceManager.GetString("NavPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплатить.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница оплаты.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнение баланса на RUNTASKER.RU.
        /// </summary>
        public static string YandexDesc {
            get {
                return ResourceManager.GetString("YandexDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через Яндекс Деньги.
        /// </summary>
        public static string YandexMoneyPM {
            get {
                return ResourceManager.GetString("YandexMoneyPM", resourceCulture);
            }
        }
    }
}
