//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runtasker.Resources.Email.OrderPerformer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PerformerOrderEmRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PerformerOrderEmRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Runtasker.Resources.Email.OrderPerformer.PerformerOrderEmRes", typeof(PerformerOrderEmRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти к моим заказам!.
        /// </summary>
        public static string ErrorFoundButtonText {
            get {
                return ResourceManager.GetString("ErrorFoundButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to о заказе №{0}.
        /// </summary>
        public static string ErrorFoundSubjectFormat {
            get {
                return ResourceManager.GetString("ErrorFoundSubjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравствуйте, {0}. Мы нашли ошибки в вашем заказе №{1}. Пожалуйста, исправьте! Это просто!.
        /// </summary>
        public static string ErrorFoundTextFormat {
            get {
                return ResourceManager.GetString("ErrorFoundTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заплатить половину!.
        /// </summary>
        public static string EstimatedBtnText {
            get {
                return ResourceManager.GetString("EstimatedBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплатить онлайн-помощь.
        /// </summary>
        public static string EstimatedOnlineHelpBtnText {
            get {
                return ResourceManager.GetString("EstimatedOnlineHelpBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Онлайн-Помощь {0}.
        /// </summary>
        public static string EstimatedOnlineHelpSubjectFormat {
            get {
                return ResourceManager.GetString("EstimatedOnlineHelpSubjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравствуйте, {0}. Онлайн-Помощь на {1} по предмету {2} стоит {3}{4}. Вам нужно оплатить всю стоимость сейчас..
        /// </summary>
        public static string EstimatedOnlineHelpTextFormat {
            get {
                return ResourceManager.GetString("EstimatedOnlineHelpTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш заказ №{0} оценили.
        /// </summary>
        public static string EstimatedSubjectFormat {
            get {
                return ResourceManager.GetString("EstimatedSubjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дорогой/ая, {0}, мы оценили ваш заказ №{1}. Ваш заказ будет стоить {2}{3}. Вам нужно оплатить половину суммы, до того как мы начнем выполнять его..
        /// </summary>
        public static string EstimatedTextFormat {
            get {
                return ResourceManager.GetString("EstimatedTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплатить и скачать!.
        /// </summary>
        public static string ExecutedButtonText {
            get {
                return ResourceManager.GetString("ExecutedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш заказ №{0} завершен.
        /// </summary>
        public static string ExecutedSubjectFormat {
            get {
                return ResourceManager.GetString("ExecutedSubjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравствуйте, {0} мы завершили работу по вашему заказу №{1}. Вы cможете скачать решение заказа, после того как оплатите - {2}{3}..
        /// </summary>
        public static string ExecutedTextFormat {
            get {
                return ResourceManager.GetString("ExecutedTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравствуйте, {0}..
        /// </summary>
        public static string GreetingFormat {
            get {
                return ResourceManager.GetString("GreetingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C наилучшими пожеланиями от Runtasker!.
        /// </summary>
        public static string RuntaskerWish {
            get {
                return ResourceManager.GetString("RuntaskerWish", resourceCulture);
            }
        }
    }
}
