//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runtasker.Resources.Views.Payment.Index {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Runtasker.Resources.Views.Payment.Index.IndexRes", typeof(IndexRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнение баланса на Runtasker.
        /// </summary>
        public static string ActionDesc {
            get {
                return ResourceManager.GetString("ActionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выберите сервис для оплаты.
        /// </summary>
        public static string ActionDescMini {
            get {
                return ResourceManager.GetString("ActionDescMini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма оплаты должна быть больше 0!.
        /// </summary>
        public static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы собираетесь пополнить баланс на Runtasker. Выберите нужный сервис для оплаты! Будьте внимательны, Robokassa имеет коммиссию 7 процентов, но позволяет проводить оплтау через WebMoney, QIWI и банковские карты. Другой сервис - YandexMoney не имеет комиссии, и также поддерживает оплату через банковские карты, вдобавок вы можете оплатить используя ваш личный онлайн кошелек YandexMoney..
        /// </summary>
        public static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата.
        /// </summary>
        public static string NavActive {
            get {
                return ResourceManager.GetString("NavActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы собираетесь пополнить баланс на Runtasker. Выберите нужный сервис для оплаты. Мы настоятельно рекомендуем вам использовать сервис ЯндексКасса. Он поддерживает все популярные способы оплаты и не имеет комиссии. Будьте внимательны, Robokassa удержит с вас коммиссию в размере 6 процентов..
        /// </summary>
        public static string NewInfoText {
            get {
                return ResourceManager.GetString("NewInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнение баланса.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнить.
        /// </summary>
        public static string TopUp {
            get {
                return ResourceManager.GetString("TopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string TopUpFormat {
            get {
                return ResourceManager.GetString("TopUpFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнить.
        /// </summary>
        public static string TopUpToHide {
            get {
                return ResourceManager.GetString("TopUpToHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через Робокассу.
        /// </summary>
        public static string ViaRobokassa {
            get {
                return ResourceManager.GetString("ViaRobokassa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через ЯндексКассу.
        /// </summary>
        public static string ViaYandexKassa {
            get {
                return ResourceManager.GetString("ViaYandexKassa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через ЯндексДеньги.
        /// </summary>
        public static string ViaYandexMoney {
            get {
                return ResourceManager.GetString("ViaYandexMoney", resourceCulture);
            }
        }
    }
}
