//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runtasker.Resources.Views.Home.Comments {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommentsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommentsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Runtasker.Resources.Views.Home.Comments.CommentsRes", typeof(CommentsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я заказываю здесь домашние работы, которые выполняются точно в срок, что для меня очень важно. А по любым вопросам всегда можно обратиться в чат, где вам помогут дружелюбные администраторы..
        /// </summary>
        public static string CommentText1 {
            get {
                return ResourceManager.GetString("CommentText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раньше домашние задания по математике занимали у меня кучу времени. Сейчас я просто отправляю их на Runtasker!.
        /// </summary>
        public static string CommentText2 {
            get {
                return ResourceManager.GetString("CommentText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Быстро, качественно и по доступной цене - всем советую!.
        /// </summary>
        public static string CommentText3 {
            get {
                return ResourceManager.GetString("CommentText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деррик Лвагула.
        /// </summary>
        public static string DerekName {
            get {
                return ResourceManager.GetString("DerekName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии наших клиентов.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Джеремиа Дисемо.
        /// </summary>
        public static string JerryName {
            get {
                return ResourceManager.GetString("JerryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Алина Киселева.
        /// </summary>
        public static string ThirdName {
            get {
                return ResourceManager.GetString("ThirdName", resourceCulture);
            }
        }
    }
}
