//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runtasker.Resources.Notifications.CustomerOrderMethods {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomerOrder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomerOrder() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Runtasker.Resources.Notifications.CustomerOrderMethods.CustomerOrder", typeof(CustomerOrder).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thank you, for your corrections! We will check this out and inform you about result!.
        /// </summary>
        public static string AddDescriptionText {
            get {
                return ResourceManager.GetString("AddDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have changed description in order #.
        /// </summary>
        public static string AddDescriptionTitle {
            get {
                return ResourceManager.GetString("AddDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Our team will check this out, we will send you the price of your order by email! Best wishes from Runtasker team!.
        /// </summary>
        public static string AddFilesText {
            get {
                return ResourceManager.GetString("AddFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thank you for adding new files to order #.
        /// </summary>
        public static string AddFilesTitle {
            get {
                return ResourceManager.GetString("AddFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We will send you the price of your order by email! Best wishes from the Runtasker team!.
        /// </summary>
        public static string AddOrderText {
            get {
                return ResourceManager.GetString("AddOrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order №.
        /// </summary>
        public static string AddOrderTitle1 {
            get {
                return ResourceManager.GetString("AddOrderTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на successfully added!.
        /// </summary>
        public static string AddOrderTitle2 {
            get {
                return ResourceManager.GetString("AddOrderTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We will improve our services!.
        /// </summary>
        public static string BadRatingText1 {
            get {
                return ResourceManager.GetString("BadRatingText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We love that you like what we do!.
        /// </summary>
        public static string GoodRatingText1 {
            get {
                return ResourceManager.GetString("GoodRatingText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User.
        /// </summary>
        public static string InvitedRatingText1 {
            get {
                return ResourceManager.GetString("InvitedRatingText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на invited you to Runtasker! Runtasker team gifts anyone.
        /// </summary>
        public static string InvitedRatingText2 {
            get {
                return ResourceManager.GetString("InvitedRatingText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на who invited someone new to our service! You can also invite your friends to us!.
        /// </summary>
        public static string InvitedRatingText3 {
            get {
                return ResourceManager.GetString("InvitedRatingText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User.
        /// </summary>
        public static string InvitedRatingTitle1 {
            get {
                return ResourceManager.GetString("InvitedRatingTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на invited.
        /// </summary>
        public static string InvitedRatingTitle2 {
            get {
                return ResourceManager.GetString("InvitedRatingTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invite User.
        /// </summary>
        public static string InviterRatingButtonText {
            get {
                return ResourceManager.GetString("InviterRatingButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have invited him/her! That&apos;s why you get your .
        /// </summary>
        public static string InviterRatingText1 {
            get {
                return ResourceManager.GetString("InviterRatingText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can invite another one!.
        /// </summary>
        public static string InviterRatingText2 {
            get {
                return ResourceManager.GetString("InviterRatingText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User.
        /// </summary>
        public static string InviterRatingTitle1 {
            get {
                return ResourceManager.GetString("InviterRatingTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на has completed his order!.
        /// </summary>
        public static string InviterRatingTitle2 {
            get {
                return ResourceManager.GetString("InviterRatingTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на #.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download Solution.
        /// </summary>
        public static string PaidAnotherHalfButtonText {
            get {
                return ResourceManager.GetString("PaidAnotherHalfButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We&apos;d like to see your comments about this work!.
        /// </summary>
        public static string PaidAnotherHalfText {
            get {
                return ResourceManager.GetString("PaidAnotherHalfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Now you can download order #.
        /// </summary>
        public static string PaidAnotherHalfTitle1 {
            get {
                return ResourceManager.GetString("PaidAnotherHalfTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на solution.
        /// </summary>
        public static string PaidAnotherHalfTitle2 {
            get {
                return ResourceManager.GetString("PaidAnotherHalfTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Our team are about to start working on your order. You will have received the solution by.
        /// </summary>
        public static string PaidFirstHalfText1 {
            get {
                return ResourceManager.GetString("PaidFirstHalfText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на at the latest..
        /// </summary>
        public static string PaidFirstHalfText2 {
            get {
                return ResourceManager.GetString("PaidFirstHalfText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have paid a half of order #.
        /// </summary>
        public static string PaidFirstHalfTitle1 {
            get {
                return ResourceManager.GetString("PaidFirstHalfTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hope to see you again!.
        /// </summary>
        public static string RatingText2 {
            get {
                return ResourceManager.GetString("RatingText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thank you for your rating!.
        /// </summary>
        public static string RatingTitle {
            get {
                return ResourceManager.GetString("RatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Best wishes from the Runtasker team!.
        /// </summary>
        public static string RuntaskerWish {
            get {
                return ResourceManager.GetString("RuntaskerWish", resourceCulture);
            }
        }
    }
}
