//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runtasker.Resources.Notifications.CustomerOrderMethods {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomerOrder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomerOrder() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Runtasker.Resources.Notifications.CustomerOrderMethods.CustomerOrder", typeof(CustomerOrder).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо, за ваши исправления! Мы проверим ваш заказ и сообщим вам о результате!.
        /// </summary>
        public static string AddDescriptionText {
            get {
                return ResourceManager.GetString("AddDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы поменяли описание в заказе №{0}..
        /// </summary>
        public static string AddDescriptionTitleFormat {
            get {
                return ResourceManager.GetString("AddDescriptionTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наша команда проверит ваш заказ, мы сообщим вам о цене вашего заказа по электронной почте! С наилучшими пожеланиями от Runtasker!.
        /// </summary>
        public static string AddFilesText {
            get {
                return ResourceManager.GetString("AddFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо, что добавили файлы в заказ №{0}..
        /// </summary>
        public static string AddFilesTitleFormat {
            get {
                return ResourceManager.GetString("AddFilesTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наша команда проверит ваш заказ, мы сообщим вам о цене вашего заказа по электронной почте! С наилучшими пожеланиями от Runtasker!.
        /// </summary>
        public static string AddOrderText {
            get {
                return ResourceManager.GetString("AddOrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказ №{0} успешно добавлен..
        /// </summary>
        public static string AddOrderTitleFormat {
            get {
                return ResourceManager.GetString("AddOrderTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы будем работать над нашим сервисом!.
        /// </summary>
        public static string BadRatingText1 {
            get {
                return ResourceManager.GetString("BadRatingText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо, что по достоинству оценили наши услуги!.
        /// </summary>
        public static string GoodRatingText1 {
            get {
                return ResourceManager.GetString("GoodRatingText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пригласить пользователя.
        /// </summary>
        public static string InviterRatingButtonText {
            get {
                return ResourceManager.GetString("InviterRatingButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы пригласили его/ee! Поэтому вы получаете {0}{1}! Также вы можете пригласить еще друзей!.
        /// </summary>
        public static string InviterRatingTextFormat {
            get {
                return ResourceManager.GetString("InviterRatingTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь {0} завершил свой заказ!..
        /// </summary>
        public static string InviterRatingTitleFormat {
            get {
                return ResourceManager.GetString("InviterRatingTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, ожидайте. Мы скоро с вами свяжемся..
        /// </summary>
        public static string OnlineHelpPaidText {
            get {
                return ResourceManager.GetString("OnlineHelpPaidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы оплатили онлайн помощь, заказ №{0}..
        /// </summary>
        public static string OnlineHelpPaidTitleFormat {
            get {
                return ResourceManager.GetString("OnlineHelpPaidTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наша команда в течение нескольких минут рассмотрит ее. Мы сообщим вам о результате..
        /// </summary>
        public static string OnlineOrderCreatedText {
            get {
                return ResourceManager.GetString("OnlineOrderCreatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы подали заявку на онлайн помощь по предмету {0}..
        /// </summary>
        public static string OnlineOrderCreatedTitleFormat {
            get {
                return ResourceManager.GetString("OnlineOrderCreatedTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачать решение.
        /// </summary>
        public static string PaidAnotherHalfButtonText {
            get {
                return ResourceManager.GetString("PaidAnotherHalfButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нам бы хотелось узнать ваше мнение о выполненной работе!.
        /// </summary>
        public static string PaidAnotherHalfText {
            get {
                return ResourceManager.GetString("PaidAnotherHalfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теперь вы можете скачать решение заказа №{0}..
        /// </summary>
        public static string PaidAnotherHalfTitleFormat {
            get {
                return ResourceManager.GetString("PaidAnotherHalfTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наша команда вскоре приступит к выполнению вашего заказа!  Вы получите решение заказа к {0} или ранее..
        /// </summary>
        public static string PaidFirstHalfTextFormat {
            get {
                return ResourceManager.GetString("PaidFirstHalfTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы оплатили половину стоимости заказа №{0}..
        /// </summary>
        public static string PaidFirstHalfTitleFormat {
            get {
                return ResourceManager.GetString("PaidFirstHalfTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Надеемся, что увидим вас снова!.
        /// </summary>
        public static string RatingText2 {
            get {
                return ResourceManager.GetString("RatingText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо, за вашу оценку!.
        /// </summary>
        public static string RatingTitle {
            get {
                return ResourceManager.GetString("RatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С наилучшими пожеланиями от Runtasker!.
        /// </summary>
        public static string RuntaskerWish {
            get {
                return ResourceManager.GetString("RuntaskerWish", resourceCulture);
            }
        }
    }
}
