//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runtasker.Resources.Views.Home.KnowPrice {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KnowPriceRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KnowPriceRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Runtasker.Resources.Views.Home.KnowPrice.KnowPriceRes", typeof(KnowPriceRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to на Runtasker.
        /// </summary>
        public static string ActionDesc3 {
            get {
                return ResourceManager.GetString("ActionDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здесь вы можете сделать свой первый {0} на Runtasker!.
        /// </summary>
        public static string ActionDescFormat {
            get {
                return ResourceManager.GetString("ActionDescFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание заказа.
        /// </summary>
        public static string ActionDescMini {
            get {
                return ResourceManager.GetString("ActionDescMini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to заказ.
        /// </summary>
        public static string ActionDescToMark {
            get {
                return ResourceManager.GetString("ActionDescToMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать заказ.
        /// </summary>
        public static string ActiveNav {
            get {
                return ResourceManager.GetString("ActiveNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать заказ.
        /// </summary>
        public static string BtnText {
            get {
                return ResourceManager.GetString("BtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, опишите ваш заказ!.
        /// </summary>
        public static string DescriptionError {
            get {
                return ResourceManager.GetString("DescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опишите ваш заказ здесь.
        /// </summary>
        public static string DescriptionPlaceholder {
            get {
                return ResourceManager.GetString("DescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, проверьте введенный вами электронный адрес!.
        /// </summary>
        public static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string HomeNav {
            get {
                return ResourceManager.GetString("HomeNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если у вас уже есть учетная запись, пожалуйста авторизуйтесь. Данная страница предназначена для регистрации и одновременного создания заказа..
        /// </summary>
        public static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком короткое имя, пожалуйста, введите свое полное имя или псевдоним!.
        /// </summary>
        public static string NameError {
            get {
                return ResourceManager.GetString("NameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, укажите ваш предмет, или выберите существующий из списка!.
        /// </summary>
        public static string OtherSubjectError {
            get {
                return ResourceManager.GetString("OtherSubjectError", resourceCulture);
            }
        }
    }
}
