//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runtasker.Resources.Views.Account.Login {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Login {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Login() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Runtasker.Resources.Views.Account.Login.Login", typeof(Login).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыли ваш пароль?.
        /// </summary>
        public static string ForgotYourPass {
            get {
                return ResourceManager.GetString("ForgotYourPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти {0}.
        /// </summary>
        public static string HeaderFormat {
            get {
                return ResourceManager.GetString("HeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to на сайт.
        /// </summary>
        public static string HeaderToMark {
            get {
                return ResourceManager.GetString("HeaderToMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string HomeNav {
            get {
                return ResourceManager.GetString("HomeNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить меня.
        /// </summary>
        public static string KeepMeSignedIn {
            get {
                return ResourceManager.GetString("KeepMeSignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрировать новый.
        /// </summary>
        public static string RegisterNew {
            get {
                return ResourceManager.GetString("RegisterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить меня.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtasker.
        /// </summary>
        public static string Runtasker {
            get {
                return ResourceManager.GetString("Runtasker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти {0}.
        /// </summary>
        public static string SocialSignInFormat {
            get {
                return ResourceManager.GetString("SocialSignInFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to через аккаунты в социальных сетях.
        /// </summary>
        public static string SocialSignInToMark {
            get {
                return ResourceManager.GetString("SocialSignInToMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to это займет всего несколько секунд.
        /// </summary>
        public static string TakesSeconds {
            get {
                return ResourceManager.GetString("TakesSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти на сайт.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти с.
        /// </summary>
        public static string VerbWith {
            get {
                return ResourceManager.GetString("VerbWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти {0}.
        /// </summary>
        public static string ViaSocialsPattern {
            get {
                return ResourceManager.GetString("ViaSocialsPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать на {0}.
        /// </summary>
        public static string WelcomeTitlePattern {
            get {
                return ResourceManager.GetString("WelcomeTitlePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еще не зарегистрированы? {0} это бесплатно!.
        /// </summary>
        public static string WithoutAccountFormat {
            get {
                return ResourceManager.GetString("WithoutAccountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите, чтобы зарегистрироваться.
        /// </summary>
        public static string WithoutAccountLinkText {
            get {
                return ResourceManager.GetString("WithoutAccountLinkText", resourceCulture);
            }
        }
    }
}
