//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runtasker.Resources.Views.Landing.AboutUs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AboutUsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutUsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Runtasker.Resources.Views.Landing.AboutUs.AboutUsRes", typeof(AboutUsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правки и доработки.
        /// </summary>
        public static string EditingAndFinilizing {
            get {
                return ResourceManager.GetString("EditingAndFinilizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtasker заботиться о своих клиентах, поэтому сопровождение ваших работ осуществляются бесплатно во время ее выполнения..
        /// </summary>
        public static string EditingAndFinilizingText {
            get {
                return ResourceManager.GetString("EditingAndFinilizingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать на {0}.
        /// </summary>
        public static string HeaderFormat {
            get {
                return ResourceManager.GetString("HeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtasker – это мультиязычное веб-приложение, созданное для студентов. Мы считаем своим долгом помочь всем студентам, поэтому мы будем продолжать добавлять новые языки в Runtasker. Для нас важно, чтобы наши заказчики при взаимодействии с нами чувствовали себя максимально комфортно. А что может быть более удобным, чем общение на родном языке?.
        /// </summary>
        public static string MiniDescription {
            get {
                return ResourceManager.GetString("MiniDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtasker?.
        /// </summary>
        public static string OrderFromUsToMark {
            get {
                return ResourceManager.GetString("OrderFromUsToMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtasker.
        /// </summary>
        public static string Runtasker {
            get {
                return ResourceManager.GetString("Runtasker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtasker : создан чтобы помогать.
        /// </summary>
        public static string Slogan {
            get {
                return ResourceManager.GetString("Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строгие сроки выполнения.
        /// </summary>
        public static string StrictTimetables {
            get {
                return ResourceManager.GetString("StrictTimetables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtasker вовремя выполняет взятые на себя обязательства. Для нас важна наша репутация..
        /// </summary>
        public static string StrictTimetablesText {
            get {
                return ResourceManager.GetString("StrictTimetablesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Техническая поддержка.
        /// </summary>
        public static string TechnicalSupport {
            get {
                return ResourceManager.GetString("TechnicalSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компания Runtasker, думает о вас и вашем времени, поэтому, наша техподдержка, всегда готова вам помочь..
        /// </summary>
        public static string TechnicalSupportText {
            get {
                return ResourceManager.GetString("TechnicalSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наверняка вы задумывались, что куча времени уходит на выполнение рутинных заданий, однотипных рефератов и прочих работ которые нужны только для «галочки»? МЫ ТОЖЕ! В Runtasker считают это недопустимой тратой времени! Поэтому всю вашу рутину мы берём на себя. НО! Как же курсовые и дипломные – это громоздкие, нудные проекты, от которых часто хочется спать? ЭТО МЫ ТОЖЕ БЕРЁМ НА СЕБЯ! Вам больше не надо тратить на это время!  Всё что вам нужно - это написать нам тему и описать ваши пожелания, и мы сделаем всё з [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TextParagraph {
            get {
                return ResourceManager.GetString("TextParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почему лучше заказывать на {0}.
        /// </summary>
        public static string WhyOrderFromUsFormat {
            get {
                return ResourceManager.GetString("WhyOrderFromUsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Качество работ.
        /// </summary>
        public static string WorksQuality {
            get {
                return ResourceManager.GetString("WorksQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компания Runtasker выполняет работы высочайшего качества. Обеспечивается это за счёт того, что над вашими заданиями трудятся настоящие профессионалы своего дела, серьезно относящиеся к своим обязанностям..
        /// </summary>
        public static string WorksQualityText {
            get {
                return ResourceManager.GetString("WorksQualityText", resourceCulture);
            }
        }
    }
}
