//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runtasker.Resources.Views.Home.News {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NewsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Runtasker.Resources.Views.Home.News.NewsRes", typeof(NewsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtasker дарит своим заказчикам {0}{1}. Эти деньги вы можете использовать для любого или даже нескольких заказов на Runtasker..
        /// </summary>
        public static string BonusMoneyTextFormat {
            get {
                return ResourceManager.GetString("BonusMoneyTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акция &quot;Бонусные деньги&quot;!.
        /// </summary>
        public static string BonusMoneyTitle {
            get {
                return ResourceManager.GetString("BonusMoneyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы сейчас находитесь на новом сайте. Теперь он мультиязычный, хорошо смотриться на вашем мобильном устройстве и гораздо удобней и функциональней по сравнению с предыдущей версией..
        /// </summary>
        public static string NewSiteText {
            get {
                return ResourceManager.GetString("NewSiteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый сайт!.
        /// </summary>
        public static string NewSiteTitle {
            get {
                return ResourceManager.GetString("NewSiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теперь мы выполняем заказы онлайн. На данный момент мы оказываем помощь только по техническим дисциплинам таким как физика, высшая математика, программирование и информатика. В будущем мы увеличим число предметов, по которым мы сможем оказать вам помощь..
        /// </summary>
        public static string OnlineHelpText {
            get {
                return ResourceManager.GetString("OnlineHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Онлайн-Помощь!.
        /// </summary>
        public static string OnlineHelpTitle {
            get {
                return ResourceManager.GetString("OnlineHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новости проекта.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
