//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runtasker.Resources.Notifications.PerformerOrderMethods {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PerformerOrderNotRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PerformerOrderNotRes() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Runtasker.Resources.Notifications.PerformerOrderMethods.PerformerOrderNotRes", typeof(PerformerOrderNotRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Description.
        /// </summary>
        public static string AddDescBtnText {
            get {
                return ResourceManager.GetString("AddDescBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please correct it!.
        /// </summary>
        public static string AddedErrorText {
            get {
                return ResourceManager.GetString("AddedErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We have found some errors! Your order #.
        /// </summary>
        public static string AddedErrorTitle {
            get {
                return ResourceManager.GetString("AddedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Files.
        /// </summary>
        public static string AddFilesBtnText {
            get {
                return ResourceManager.GetString("AddFilesBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay.
        /// </summary>
        public static string EstimatedBtnText {
            get {
                return ResourceManager.GetString("EstimatedBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your order #.
        /// </summary>
        public static string EstimatedText1 {
            get {
                return ResourceManager.GetString("EstimatedText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на costs.
        /// </summary>
        public static string EstimatedText2 {
            get {
                return ResourceManager.GetString("EstimatedText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please, pay half of the sum now.
        /// </summary>
        public static string EstimatedText3 {
            get {
                return ResourceManager.GetString("EstimatedText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your order has been estimated..
        /// </summary>
        public static string EstimatedTitle1 {
            get {
                return ResourceManager.GetString("EstimatedTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay.
        /// </summary>
        public static string ExecutedBtnText {
            get {
                return ResourceManager.GetString("ExecutedBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay the second half of the price and get the solution!.
        /// </summary>
        public static string ExecutedText1 {
            get {
                return ResourceManager.GetString("ExecutedText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string ExecutedText2 {
            get {
                return ResourceManager.GetString("ExecutedText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We have completed working on your order #.
        /// </summary>
        public static string ExecutedTitle1 {
            get {
                return ResourceManager.GetString("ExecutedTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Best wishes from the Runtasker team!.
        /// </summary>
        public static string RuntaskerWishes {
            get {
                return ResourceManager.GetString("RuntaskerWishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Our team have started working on your order. You will have received the solution by.
        /// </summary>
        public static string StartedExecutingText1 {
            get {
                return ResourceManager.GetString("StartedExecutingText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на at the latest..
        /// </summary>
        public static string StartedExecutingText2 {
            get {
                return ResourceManager.GetString("StartedExecutingText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your order #.
        /// </summary>
        public static string StartedExecutingTitle1 {
            get {
                return ResourceManager.GetString("StartedExecutingTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is being carried out..
        /// </summary>
        public static string StartedExecutingTitle2 {
            get {
                return ResourceManager.GetString("StartedExecutingTitle2", resourceCulture);
            }
        }
    }
}
