//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runtasker.Resources.Views.Landing.Pricing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PricingRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PricingRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Runtasker.Resources.Views.Landing.Pricing.PricingRes", typeof(PricingRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связь с исполнителем любым удобным способом.
        /// </summary>
        public static string AnyTypeOfConnection {
            get {
                return ResourceManager.GetString("AnyTypeOfConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возможность обсудить работу напрямую с исполнителем.
        /// </summary>
        public static string DiscussWithPerformer {
            get {
                return ResourceManager.GetString("DiscussWithPerformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узнать цену моей работы.
        /// </summary>
        public static string FindOutThePrice {
            get {
                return ResourceManager.GetString("FindOutThePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бесплатные доработки.
        /// </summary>
        public static string FreeCorrections {
            get {
                return ResourceManager.GetString("FreeCorrections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бесплатное повышение уникальности текста.
        /// </summary>
        public static string FreeUniqueTextUpgrade {
            get {
                return ResourceManager.GetString("FreeUniqueTextUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to от {0}{1}.
        /// </summary>
        public static string FromPriceFormat {
            get {
                return ResourceManager.GetString("FromPriceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказать Онлайн-Помощь.
        /// </summary>
        public static string OrderOnlineHelp {
            get {
                return ResourceManager.GetString("OrderOnlineHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возможность оплатить бонусными деньгами.
        /// </summary>
        public static string PayWithBonusMoney {
            get {
                return ResourceManager.GetString("PayWithBonusMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гарантия возврата средств при неудаче исполнителя.
        /// </summary>
        public static string ReturningFundsWarranty {
            get {
                return ResourceManager.GetString("ReturningFundsWarranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение вашего заказа в очень сжатые сроки.
        /// </summary>
        public static string ShortTimeExecution {
            get {
                return ResourceManager.GetString("ShortTimeExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наши цены.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
