//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runtasker.Resources.Email.OrderCustomer {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustEmailNotRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustEmailNotRes() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Runtasker.Resources.Email.OrderCustomer.CustEmailNotRes", typeof(CustEmailNotRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на about order #.
        /// </summary>
        public static string AddedSubject1 {
            get {
                return ResourceManager.GetString("AddedSubject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We have received your order #.
        /// </summary>
        public static string AddedText1 {
            get {
                return ResourceManager.GetString("AddedText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на that you created. Our administrators will process it and get back to you with the price..
        /// </summary>
        public static string AddedText2 {
            get {
                return ResourceManager.GetString("AddedText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dear.
        /// </summary>
        public static string Dear {
            get {
                return ResourceManager.GetString("Dear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to my orders!.
        /// </summary>
        public static string DownloadedBtnText {
            get {
                return ResourceManager.GetString("DownloadedBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You downloaded solution!.
        /// </summary>
        public static string DownloadedSubject1 {
            get {
                return ResourceManager.GetString("DownloadedSubject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You downloaded your order.
        /// </summary>
        public static string DownloadedText1 {
            get {
                return ResourceManager.GetString("DownloadedText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на solution! Tell us about the result of our work! We&apos;re not hurring you up with that! Do that any time you want! Hope to see you again on Runtasker!.
        /// </summary>
        public static string DownloadedText2 {
            get {
                return ResourceManager.GetString("DownloadedText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You paid a half of an order #.
        /// </summary>
        public static string FirstPaidSubject1 {
            get {
                return ResourceManager.GetString("FirstPaidSubject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на you paid a half of an order #.
        /// </summary>
        public static string FirstPaidText1 {
            get {
                return ResourceManager.GetString("FirstPaidText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Our team will start executing it immediately! You&apos;ll get the solution till.
        /// </summary>
        public static string FirstPaidText2 {
            get {
                return ResourceManager.GetString("FirstPaidText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на or earlier. We will inform you by email when it&apos;s done!.
        /// </summary>
        public static string FirstPaidText3 {
            get {
                return ResourceManager.GetString("FirstPaidText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spend my bonus money!.
        /// </summary>
        public static string InvFinishedBtnText {
            get {
                return ResourceManager.GetString("InvFinishedBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You get 300 roubles!.
        /// </summary>
        public static string InvFinishedSubject1 {
            get {
                return ResourceManager.GetString("InvFinishedSubject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на got his order finished!.
        /// </summary>
        public static string InvFinishedText1 {
            get {
                return ResourceManager.GetString("InvFinishedText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You invited him/her to us! That means you get your 300 roubles! Hope to see you and your friends on Runtasker!.
        /// </summary>
        public static string InvFinishedText2 {
            get {
                return ResourceManager.GetString("InvFinishedText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Best wishes from the Runtasker team!.
        /// </summary>
        public static string RuntaskerWish {
            get {
                return ResourceManager.GetString("RuntaskerWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
