//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runtasker.Resources.Email.OrderCustomer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustEmailNotRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustEmailNotRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Runtasker.Resources.Email.OrderCustomer.CustEmailNotRes", typeof(CustEmailNotRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to о заказе №{0}..
        /// </summary>
        public static string AddedSubjectFormat {
            get {
                return ResourceManager.GetString("AddedSubjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уважаемый/ая, {0}, вы создали заказ №{1}. Мы его получили, наши администраторы уже проверяют его, мы сообщим вам цену по электронной почте..
        /// </summary>
        public static string AddedTextFormat {
            get {
                return ResourceManager.GetString("AddedTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уважаемый/ая.
        /// </summary>
        public static string Dear {
            get {
                return ResourceManager.GetString("Dear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти к моим заказам!.
        /// </summary>
        public static string DownloadedBtnText {
            get {
                return ResourceManager.GetString("DownloadedBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы только что скачали решение заказа {0}..
        /// </summary>
        public static string DownloadedSubjectFormat {
            get {
                return ResourceManager.GetString("DownloadedSubjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уважаемый/ая, {0}, вы скачали решение заказа №{1}. ! Расскажите нам о результате. Мы не торопим вас с этим. Сделайте это тогда, когда вам удобно. Надеемся увидеть вас снова на Runtasker!.
        /// </summary>
        public static string DownloadedTextFormat {
            get {
                return ResourceManager.GetString("DownloadedTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы оплатили половину заказа №{0}.
        /// </summary>
        public static string FirstPaidSubjectFormat {
            get {
                return ResourceManager.GetString("FirstPaidSubjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уважаемый/ая, {0}, вы оплатили половину заказа №{1}. Наша команда скоро начнет выполнять его! Вы получите решение к {2} или ранее. Мы сообщим вам, как только закончим!.
        /// </summary>
        public static string FirstPaidTextFormat {
            get {
                return ResourceManager.GetString("FirstPaidTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравствуйте, {0}..
        /// </summary>
        public static string HelloFormat {
            get {
                return ResourceManager.GetString("HelloFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уважаемый/ая, {0}, вы подали заявку на онлайн помощь по предмету {1}. Мы ее получили, наши администраторы уже проверяют вашу заявку, мы сообщим вам о результате по электронной почте..
        /// </summary>
        public static string OnlineHelpAppliedTextFormat {
            get {
                return ResourceManager.GetString("OnlineHelpAppliedTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С наилучшими пожеланиями от Runtasker!.
        /// </summary>
        public static string RuntaskerWish {
            get {
                return ResourceManager.GetString("RuntaskerWish", resourceCulture);
            }
        }
    }
}
